version: '3.8'

services:
  api_roles:
    container_name: backend_roles
    build: .
    ports:
      - 3005:3005
    environment:
      PORT: 3005
    env_file: .env
    volumes:
      - ./:/code
      - node_modules:/code/node_modules
    networks:
      - backend_roles
      - siged_backend
    depends_on:
      - db_roles

  db_roles:
    container_name: db_roles
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db-role
    env_file: .env
    volumes:
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./db/.dbshell:/home/mongodb/.dbshell
      - mongodb:/data/db
    networks:
      - backend_roles

volumes:
  node_modules:
  mongodb:


networks:
  backend_roles:
  siged_backend:
    external: true
